AWSTemplateFormatVersion: '2010-09-09'
Description: HTTP API + Lambda para crear usuarios en DynamoDB (código desde S3). La Lambda escribe en la tabla 'UserManagementTable' por defecto.

Parameters:
  ProjectName:
    Type: String
    Default: events-app
    Description: Prefijo para nombrar recursos.
  TableName:
    Type: String
    Default: UserManagementTable
    Description: Nombre FÍSICO de la tabla DynamoDB donde se crearán usuarios (por defecto: UserManagementTable).
  CodeS3Bucket:
    Type: String
    Description: Bucket S3 donde está el paquete ZIP de la Lambda
  CodeS3Key:
    Type: String
    Description: Key del ZIP de la Lambda (por ej: lambda/users_create.zip)
  LambdaMemoryMB:
    Type: Number
    Default: 512
  LambdaTimeoutSec:
    Type: Number
    Default: 15

Resources:

  UsersLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-users-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: [lambda.amazonaws.com] }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}/index/*

  CreateUserLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-create-user
      Runtime: python3.12
      Handler: app.handler
      Role: !GetAtt UsersLambdaRole.Arn
      MemorySize: !Ref LambdaMemoryMB
      Timeout: !Ref LambdaTimeoutSec
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Architectures: [arm64]

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub ${ProjectName}-httpapi
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['POST', 'OPTIONS']
        AllowHeaders: ['content-type', 'authorization']

  ApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateUserLambda.Arn}/invocations
      PayloadFormatVersion: '2.0'

  PostUsersRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /users'
      Target: !Sub integrations/${ApiIntegration}

  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: v1
      AutoDeploy: true

  ApiInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CreateUserLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      # Permite invocaciones desde cualquier método/ruta de este API y stage
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/*

Outputs:
  ApiBaseUrl:
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/v1
    Description: URL base del API
  CreateUserEndpoint:
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/v1/users
    Description: Endpoint POST para crear usuarios
  LambdaName:
    Value: !Ref CreateUserLambda
  LambdaRoleName:
    Value: !Ref UsersLambdaRole
