AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway REST (API compartido) + Lambda para crear eventos

Parameters:
  ProjectName:
    Type: String
    Default: events-app
  CodeS3Bucket:
    Type: String
  CodeS3Key:
    Type: String
  LambdaRoleArn:
    Type: String
    Description: ARN del rol EXISTENTE para la Lambda (no se crea en este stack)
  StageName:
    Type: String
    Default: prod
  RestApiId:
    Type: String
  RootResourceId:
    Type: String

Resources:
  CreateEventLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-create-event-lambda'
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !Ref LambdaRoleArn
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Environment:
        Variables:
          EVENTS_TABLE: EventManagementTable
          USERS_TABLE: UserManagementTable
      Timeout: 15
      MemorySize: 256
      TracingConfig:
        Mode: PassThrough

  EventsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiId
      ParentId: !Ref RootResourceId
      PathPart: events

  EventsPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId
      ResourceId: !Ref EventsResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateEventLambdaFunction.Arn}/invocations'

  CreateEventLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CreateEventLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/POST/events'

Outputs:
  EventsInvokeUrl:
    Description: URL del endpoint POST /events (requiere deployment a la stage)
    Value: !Sub 'https://${RestApiId}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/events'
