AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB - Tablas de clientes, registro de ventes y eventos



Resources:
  EventManagementTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: EventManagementTable  # Nombre fijo de la tabla
      BillingMode: PAY_PER_REQUEST  # Modo On-Demand - pago por uso real
      AttributeDefinitions: # Solo atributos usados en keys o indices
        - AttributeName: EventId
          AttributeType: S  # String
        - AttributeName: EventName
          AttributeType: S
        - AttributeName: EventDate
          AttributeType: S
        - AttributeName: EventStatus
          AttributeType: S
        - AttributeName: EventCountry
          AttributeType: S
        - AttributeName: EventCity
          AttributeType: S
      KeySchema: # Definicion de la clave primaria
        - AttributeName: EventId
          KeyType: HASH  # Partition key
      GlobalSecondaryIndexes: # Indices para consultas alternativas
        - IndexName: EventNameIndex
          KeySchema:
            - AttributeName: EventName
              KeyType: HASH
          Projection: # Que atributos incluir en el indice
            ProjectionType: ALL  # Incluye todos los atributos
        - IndexName: EventCountryCityIndex
          KeySchema:
            - AttributeName: EventCountry
              KeyType: HASH  # Partition key del indice
            - AttributeName: EventCity
              KeyType: RANGE  # Sort key del indice
          Projection:
            ProjectionType: ALL
        - IndexName: EventStatusIndex
          KeySchema:
            - AttributeName: EventStatus
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: EventDateIndex
          KeySchema:
            - AttributeName: EventDate
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      #PointInTimeRecoverySpecification: # Backup continuo
      #  PointInTimeRecoveryEnabled: true
      #DeletionProtection: true  # Protege contra eliminacion accidental

  # DynamoDB Table for User Management
  UserManagementTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: UserManagementTable  # Nombre fijo de la tabla
      BillingMode: PAY_PER_REQUEST  # Modo On-Demand - pago por uso real
      AttributeDefinitions: # Solo atributos usados en keys o indices
        - AttributeName: UserId
          AttributeType: S  # String
        - AttributeName: UserNames
          AttributeType: S
        - AttributeName: UserEmail
          AttributeType: S
      KeySchema: # Definicion de la clave primaria
        - AttributeName: UserId
          KeyType: HASH  # Partition key
      GlobalSecondaryIndexes: # Indices para consultas alternativas
        - IndexName: UserNamesIndex
          KeySchema:
            - AttributeName: UserNames
              KeyType: HASH
          Projection: # Que atributos incluir en el indice
            ProjectionType: ALL  # Incluye todos los atributos
        - IndexName: UserEmailIndex
          KeySchema:
            - AttributeName: UserEmail
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      #PointInTimeRecoverySpecification: # Backup continuo
      #  PointInTimeRecoveryEnabled: true
      #DeletionProtection: true  # Protege contra eliminacion accidental

  # DynamoDB Table for Registration
  RegistrationTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: RegistrationTable  # Nombre fijo de la tabla
      BillingMode: PAY_PER_REQUEST  # Modo On-Demand - pago por uso real
      AttributeDefinitions: # Solo atributos usados en keys o indices
        - AttributeName: RegistrationId
          AttributeType: S  # String
        - AttributeName: RegistrationDate
          AttributeType: S
        - AttributeName: RegistrationEventId
          AttributeType: S
        - AttributeName: RegistrationUserId
          AttributeType: S
      KeySchema: # Definicion de la clave primaria
        - AttributeName: RegistrationId
          KeyType: HASH  # Partition key
      GlobalSecondaryIndexes: # Indices para consultas alternativas
        - IndexName: RegistrationDateIndex
          KeySchema:
            - AttributeName: RegistrationDate
              KeyType: HASH
          Projection: # Que atributos incluir en el indice
            ProjectionType: ALL  # Incluye todos los atributos
        - IndexName: RegistrationEventIdIndex
          KeySchema:
            - AttributeName: RegistrationEventId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: RegistrationUserIdIndex
          KeySchema:
            - AttributeName: RegistrationUserId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      #PointInTimeRecoverySpecification: # Backup continuo
      #  PointInTimeRecoveryEnabled: true
      #DeletionProtection: true  # Protege contra eliminacion accidental

  #######################################################################################################################################
  # A continuacion los outputs que se generan despues de crear la infraestructura
  #######################################################################################################################################


Outputs:
  EventManagementTableName:
    Description: "Nombre de la tabla DynamoDB de Event Management"
    Value: !Ref EventManagementTable
    Export:
      Name: EventTableName

  UserManagementTableName:
    Description: "Nombre de la tabla DynamoDB de User Management"
    Value: !Ref UserManagementTable
    Export:
      Name: UserTableName

  RegistrationTableName:
    Description: "Nombre de la tabla DynamoDB de Registration"
    Value: !Ref RegistrationTable
    Export:
      Name: RegistrationTableName