AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB - Tablas de clientes, registro de ventes y eventos



Resources:
  EventManagementTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: EventManagementTable
      BillingMode: PAY_PER_REQUEST
      # La unión exacta de TODAS las claves usadas por la tabla y sus GSIs
      AttributeDefinitions:
        - AttributeName: EventId
          AttributeType: S
        - AttributeName: EventName
          AttributeType: S
        - AttributeName: EventDate
          AttributeType: S
        - AttributeName: EventStatus
          AttributeType: S
        - AttributeName: EventCountry
          AttributeType: S
        - AttributeName: EventCity
          AttributeType: S
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: Quantity
          AttributeType: N
      KeySchema:
        - AttributeName: EventId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EventNameIndex
          KeySchema:
            - AttributeName: EventName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: EventCountryCityIndex
          KeySchema:
            - AttributeName: EventCountry
              KeyType: HASH
            - AttributeName: EventCity
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: EventStatusIndex
          KeySchema:
            - AttributeName: EventStatus
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: EventDateIndex
          KeySchema:
            - AttributeName: EventDate
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        # ↓ Nuevos GSIs para tus campos "fundamentales"
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: UserId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: QuantityIndex
          KeySchema:
            - AttributeName: Quantity
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      #PointInTimeRecoverySpecification: # Backup continuo
      #  PointInTimeRecoveryEnabled: true
      #DeletionProtection: true  # Protege contra eliminacion accidental

  # DynamoDB Table for User Management
  UserManagementTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: UserManagementTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: UserNames
          AttributeType: S
        - AttributeName: UserEmail
          AttributeType: S
        - AttributeName: Role
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserNamesIndex
          KeySchema:
            - AttributeName: UserNames
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: UserEmailIndex
          KeySchema:
            - AttributeName: UserEmail
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: RoleIndex
          KeySchema:
            - AttributeName: Role
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # DynamoDB Table for Registration
  RegistrationTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: RegistrationTable  # Nombre fijo de la tabla
      BillingMode: PAY_PER_REQUEST  # Modo On-Demand - pago por uso real
      AttributeDefinitions: # Solo atributos usados en keys o indices
        - AttributeName: RegistrationId
          AttributeType: S  # String
        - AttributeName: RegistrationDate
          AttributeType: S
        - AttributeName: RegistrationEventId
          AttributeType: S
        - AttributeName: RegistrationUserId
          AttributeType: S
      KeySchema: # Definicion de la clave primaria
        - AttributeName: RegistrationId
          KeyType: HASH  # Partition key
      GlobalSecondaryIndexes: # Indices para consultas alternativas
        - IndexName: RegistrationDateIndex
          KeySchema:
            - AttributeName: RegistrationDate
              KeyType: HASH
          Projection: # Que atributos incluir en el indice
            ProjectionType: ALL  # Incluye todos los atributos
        - IndexName: RegistrationEventIdIndex
          KeySchema:
            - AttributeName: RegistrationEventId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: RegistrationUserIdIndex
          KeySchema:
            - AttributeName: RegistrationUserId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      #PointInTimeRecoverySpecification: # Backup continuo
      #  PointInTimeRecoveryEnabled: true
      #DeletionProtection: true  # Protege contra eliminacion accidental

  #######################################################################################################################################
  # A continuacion los outputs que se generan despues de crear la infraestructura
  #######################################################################################################################################


Outputs:
  EventManagementTableName:
    Description: "Nombre de la tabla DynamoDB de Event Management"
    Value: !Ref EventManagementTable
    Export:
      Name: EventTableName

  UserManagementTableName:
    Description: "Nombre de la tabla DynamoDB de User Management"
    Value: !Ref UserManagementTable
    Export:
      Name: UserTableName

  RegistrationTableName:
    Description: "Nombre de la tabla DynamoDB de Registration"
    Value: !Ref RegistrationTable
    Export:
      Name: RegistrationTableName

  EventManagementTable:
    Description: ARN de la tabla de eventos
    Value: !GetAtt EventManagementTable.Arn
    Export:
      Name: !Sub "EventTableArn"

  UserManagementTable:
    Description: ARN de la tabla de usuarios
    Value: !GetAtt UserManagementTable.Arn
    Export:
      Name: !Sub "UserTableArn"

  RegistrationTableArn:
    Description: ARN de la tabla de registros
    Value: !GetAtt RegistrationTable.Arn
    Export:
      Name: !Sub "RegistrationTableArn"