AWSTemplateFormatVersion: '2010-09-09'
Description: >
  DynamoDB - Tabla única para EventsApp (modo On-Demand).
  Incluye GSIs para consultas por estado, organizador y usuario.

Parameters:
  ProjectName:
    Type: String
    Default: events-app
    Description: Prefijo para nombrar la tabla.

Resources:

  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-EventsApp
      BillingMode: PAY_PER_REQUEST   # Escalado automático
      SSESpecification:
        SSEEnabled: true             # Cifrado administrado por AWS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TimeToLiveSpecification:
        AttributeName: expiresAt     # opcional (epoch segundos)
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S

        # GSI1: Eventos por estado y fecha
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S

        # GSI2: Eventos por organizador y fecha
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S

        # GSI3: Inscripciones por usuario
        - AttributeName: GSI3PK
          AttributeType: S
        - AttributeName: GSI3SK
          AttributeType: S

      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: GSI3
          KeySchema:
            - AttributeName: GSI3PK
              KeyType: HASH
            - AttributeName: GSI3SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: stack
          Value: dynamodb

Outputs:
  TableName:
    Value: !Ref EventsTable
    Description: Nombre de la tabla DynamoDB
  TableArn:
    Value: !GetAtt EventsTable.Arn
    Description: ARN de la tabla
  TableStreamArn:
    Value: !GetAtt EventsTable.StreamArn
    Description: ARN del stream (para Lambda triggers si los usas)
