AWSTemplateFormatVersion: '2010-09-09'
Description: Bucket S3 para almacenar paquetes ZIP de Lambdas

Parameters:
  ProjectName:
    Type: String
    Default: events-app

Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-lambda-code-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-reports-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256



Outputs:
  BucketName:
    Value: !Ref LambdaCodeBucket
    Description: Nombre del bucket para subir los ZIP de la Lambda
  ReportsBucketName:
    Description: Nombre del bucket de reportes
    Value: !Ref ReportsBucket
    Export:
      Name: !Sub "${ProjectName}-ReportsBucketName"
  ReportsBucketArn:
    Description: ARN del bucket de reportes
    Value: !GetAtt ReportsBucket.Arn
    Export:
      Name: !Sub "${ProjectName}-ReportsBucketArn"