AWSTemplateFormatVersion: '2010-09-09'
Description: Bucket S3 para almacenar paquetes ZIP de Lambdas

Parameters:
  ProjectName:
    Type: String
    Default: events-app

Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-lambda-code-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Value: !Ref LambdaCodeBucket
    Description: Nombre del bucket para subir los ZIP de la Lambda