name: Deploy (main)

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - 'lambda/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2
  PROJECT_NAME: events-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Create S3 code bucket stack
        run: |
          aws cloudformation deploy \
            --template-file infra/s3-code-bucket.yaml \
            --stack-name ${{ env.PROJECT_NAME }}-lambda-code-bucket \
            --parameter-overrides ProjectName=${{ env.PROJECT_NAME }} \
            --region ${{ env.AWS_REGION }}

      - name: Zip Lambda
        run: |
          mkdir -p dist
          cd lambda/users_create
          zip -r ../../dist/users_create.zip app.py

      - name: Zip Lambda event
        run: |
          mkdir -p dist
          cd lambda/add_event
          zip -r ../../dist/add_event.zip app.py

      - name: Zip Lambda registration
        run: |
          mkdir -p dist
          cd lambda/add_compra
          zip -r ../../dist/add_compra.zip app.py

      - name: Upload ZIP to S3
        run: |
          CODE_S3_KEY=lambda/users_create-${GITHUB_SHA}.zip
          echo "CODE_S3_KEY=$CODE_S3_KEY" >> $GITHUB_ENV
          aws s3 cp dist/users_create.zip "s3://events-app-lambda-code-884234865118-us-west-2/$CODE_S3_KEY" --region ${AWS_REGION}

      - name: Upload ZIP to S3 event
        run: |
          CODE_S3_KEY_EVENT=lambda/add_event-${GITHUB_SHA}.zip
          echo "CODE_S3_KEY_EVENT=$CODE_S3_KEY_EVENT" >> $GITHUB_ENV
          aws s3 cp dist/add_event.zip "s3://events-app-lambda-code-884234865118-us-west-2/$CODE_S3_KEY_EVENT" --region ${AWS_REGION}

      - name: Upload ZIP to S3 sell
        run: |
          CODE_S3_KEY_SELL=lambda/add_compra-${GITHUB_SHA}.zip
          echo "CODE_S3_KEY_SELL=$CODE_S3_KEY_SELL" >> $GITHUB_ENV
          aws s3 cp dist/add_event.zip "s3://events-app-lambda-code-884234865118-us-west-2/$CODE_S3_KEY_SELL" --region ${AWS_REGION}


      - name: Deploy DynamoDB tables
        run: |
          aws cloudformation deploy \
            --stack-name "${PROJECT_NAME}-dynamodb" \
            --template-file infra/dynamodb.yaml \
            --parameter-overrides ProjectName="${PROJECT_NAME}" \
            --region "${AWS_REGION}"

      - name: Lambda
        run: |
          aws cloudformation deploy \
            --template-file infra/lambda-events.yaml \
            --stack-name ${PROJECT_NAME}-users-api \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              ProjectName=${PROJECT_NAME} \
              CodeS3Bucket=${CODE_BUCKET} \
              CodeS3Key=${CODE_S3_KEY} \
              CodeS3KeyEvent=${CODE_S3_KEY_EVENT} \
            --region ${AWS_REGION}

      - name: Deploy API
        run: |
          aws cloudformation deploy \
            --template-file infra/restapi.yaml \
            --stack-name ${PROJECT_NAME}-restapi \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              ProjectName=${PROJECT_NAME} \
              DeploymentVersion=1.0.0 \
            --region ${AWS_REGION}

      - name: Summary
        run: echo "✅ Deploy OK" >> $GITHUB_STEP_SUMMARY
